# Python Interactive Maps with Folium

# Notes

* folium is similar to ipyleaflet but different in some functionaly and syntax
* for install instructions go to python.org, python package index, search for folium

# Data Files

* indiana_outline_map.geojson
* sales_region1.geojson
* sales_region2.geojson
* sales_region3.geojson
* geojson_indianacounties.geojson
* indiana_population_by_county.csv
* flags_of_africa.png (from Wikipedia)

# Documentation

In [1]:
from IPython.display import IFrame
documentation = IFrame(src='https://python-visualization.github.io/folium/', width=1000, height=500)
display(documentation)

# Imports

In [1]:
import folium # pip install folium
from folium import plugins
import ipywidgets
import geocoder # pip install geocoder
import geopy # pip install geopy
import numpy as np
import pandas as pd
from vega_datasets import data as vds # pip install vega_datasets

# Basic Maps

In [2]:
folium.Map?

Init signature:
folium.Map(
    location=None,
    width='100%',
    height='100%',
    left='0%',
    top='0%',
    position='relative',
    tiles='OpenStreetMap',
    attr=None,
    min_zoom=0,
    max_zoom=18,
    zoom_start=10,
    min_lat=-90,
    max_lat=90,
    min_lon=-180,
    max_lon=180,
    max_bounds=False,
    crs='EPSG3857',
    control_scale=False,
    prefer_canvas=False,
    no_touch=False,
    disable_3d=False,
    png_enabled=False,
    zoom_control=True,
    **kwargs,
)
Docstring:
Create a Map with Folium and Leaflet.js

Generate a base map of given width and height with either default
tilesets or a custom tileset URL. The following tilesets are built-in
to Folium. Pass any of the following to the "tiles" keyword:

    - "OpenStreetMap"
    - "Mapbox Bright" (Limited levels of zoom for free tiles)
    - "Mapbox Control Room" (Limited levels of zoom for free tiles)
    - "Stamen" (Terrain, Toner, and Watercolor)
    - "Cloudmade" (Must pass API key)
    - "Mapbox" (Must pass API key)
    - "CartoDB" (positron and dark_matter)

You can pass a custom tileset to Folium by passing a Leaflet-style
URL to the tiles parameter: ``http://{s}.yourtiles.com/{z}/{x}/{y}.png``.

You can find a list of free tile providers here:
``http://leaflet-extras.github.io/leaflet-providers/preview/``.
Be sure to check their terms and conditions and to provide attribution
with the `attr` keyword.

Parameters
----------
location: tuple or list, default None
    Latitude and Longitude of Map (Northing, Easting).
width: pixel int or percentage string (default: '100%')
    Width of the map.
height: pixel int or percentage string (default: '100%')
    Height of the map.
tiles: str, default 'OpenStreetMap'
    Map tileset to use. Can choose from a list of built-in tiles,
    pass a custom URL or pass `None` to create a map without tiles.
    For more advanced tile layer options, use the `TileLayer` class.
min_zoom: int, default 0
    Minimum allowed zoom level for the tile layer that is created.
max_zoom: int, default 18
    Maximum allowed zoom level for the tile layer that is created.
zoom_start: int, default 10
    Initial zoom level for the map.
attr: string, default None
    Map tile attribution; only required if passing custom tile URL.
crs : str, default 'EPSG3857'
    Defines coordinate reference systems for projecting geographical points
    into pixel (screen) coordinates and back.
    You can use Leaflet's values :
    * EPSG3857 : The most common CRS for online maps, used by almost all
    free and commercial tile providers. Uses Spherical Mercator projection.
    Set in by default in Map's crs option.
    * EPSG4326 : A common CRS among GIS enthusiasts.
    Uses simple Equirectangular projection.
    * EPSG3395 : Rarely used by some commercial tile providers.
    Uses Elliptical Mercator projection.
    * Simple : A simple CRS that maps longitude and latitude into
    x and y directly. May be used for maps of flat surfaces
    (e.g. game maps). Note that the y axis should still be inverted
    (going from bottom to top).
control_scale : bool, default False
    Whether to add a control scale on the map.
prefer_canvas : bool, default False
    Forces Leaflet to use the Canvas back-end (if available) for
    vector layers instead of SVG. This can increase performance
    considerably in some cases (e.g. many thousands of circle
    markers on the map).
no_touch : bool, default False
    Forces Leaflet to not use touch events even if it detects them.
disable_3d : bool, default False
    Forces Leaflet to not use hardware-accelerated CSS 3D
    transforms for positioning (which may cause glitches in some
    rare environments) even if they're supported.
zoom_control : bool, default True
    Display zoom controls on the map.
**kwargs
    Additional keyword arguments are passed to Leaflets Map class:
    https://leafletjs.com/reference-1.6.0.html#map

Returns
-------
Folium Map Object

Examples
--------
>>> m = folium.Map(location=[45.523, -122.675], width=750, height=500)
>>> m = folium.Map(location=[45.523, -122.675], tiles='cartodb positron')
>>> m = folium.Map(
...    location=[45.523, -122.675],
...    zoom_start=2,
...    tiles='https://api.mapbox.com/v4/mapbox.streets/{z}/{x}/{y}.png?access_token=mytoken',
...    attr='Mapbox attribution'
...)
File:           c:\users\miguel angel\appdata\local\programs\python\python37\lib\site-packages\folium\folium.py
Type:           type
Subclasses:

In [3]:
folium.Map()

In [4]:
map1 = folium.Map(location=[40.4167, -3.6840],
                 zoom_start=14,
                 width=700,
                 height=500,
                 control_scale=True)
map1

In [5]:
# another way to change map size

from branca.element import Figure

fig = Figure(width=700, height=500)
fig.add_child(map1)
fig

# Save Map

In [6]:
map1.save('map1.html')

# Map Types

In [7]:
# widget
select_widget=ipywidgets.Select(
    options=['Open Street Map', 'Terrain', 'Toner', 'Watercolor', 'Positron', 'Dark Matter'],
    value='Open Street Map',
    description='Map Type:',
    disabled=False)

# widget function
def select(map_type):
    if map_type == 'Open Street Map':
        display(folium.Map(location=[40.416719, -3.684016], zoom_start=12, height=500))
    if map_type == 'Terrain':
        display(folium.Map(location=[40.416719, -3.684016], tiles='Stamen Terrain', zoom_start=12, height=400))
    if map_type == 'Toner':
        display(folium.Map(location=[40.416719, -3.684016], tiles='Stamen Toner', zoom_start=12, height=400))
    if map_type == 'Watercolor':
        display(folium.Map(location=[40.416719, -3.684016], tiles='Stamen Watercolor', zoom_start=12, height=400))
    if map_type == 'Positron':
        display(folium.Map(location=[40.416719, -3.684016], tiles='CartoDB Positron', zoom_start=12, height=400))
    if map_type == 'Dark Matter':
        display(folium.Map(location=[40.416719, -3.684016], tiles='CartoDB Dark_Matter', zoom_start=12, height=400))
        
# interaction between widgets and function    
ipywidgets.interact(select, map_type=select_widget);

interactive(children=(Select(description='Map Type:', options=('Open Street Map', 'Terrain', 'Toner', 'Waterco…

In [10]:
# show map types using layer control
# Layers: https://deparkes.co.uk/2016/06/10/folium-map-tiles/

# map
map_layer_control = folium.Map(location=[40.416719, -3.684016], zoom_start=12)

# add tiles to map
folium.raster_layers.TileLayer('Open Street Map').add_to(map_layer_control)
folium.raster_layers.TileLayer('Stamen Terrain').add_to(map_layer_control)
folium.raster_layers.TileLayer('Stamen Toner').add_to(map_layer_control)
folium.raster_layers.TileLayer('Stamen Watercolor').add_to(map_layer_control)
folium.raster_layers.TileLayer('CartoDB Positron').add_to(map_layer_control)
folium.raster_layers.TileLayer('CartoDB Dark_Matter').add_to(map_layer_control)

# add layer control to show different maps
folium.LayerControl().add_to(map_layer_control)

# display map
map_layer_control

In [11]:
map_with_mini = folium.Map(location=[40.416719, -3.684016], zoom_start=7)

minimap = plugins.MiniMap(toggle_display = True)

map_with_mini.add_child(minimap)

plugins.Fullscreen(position = 'topright').add_to(map_with_mini)
map_with_mini.save('map_with_mini.html')
map_with_mini

# Markers

In [12]:
folium.Marker?

Init signature:
folium.Marker(
    location=None,
    popup=None,
    tooltip=None,
    icon=None,
    draggable=False,
    **kwargs,
)
Docstring:
Create a simple stock Leaflet marker on the map, with optional
popup text or Vincent visualization.

Parameters
----------
location: tuple or list
    Latitude and Longitude of Marker (Northing, Easting)
popup: string or folium.Popup, default None
    Label for the Marker; either an escaped HTML string to initialize
    folium.Popup or a folium.Popup instance.
tooltip: str or folium.Tooltip, default None
    Display a text when hovering over the object.
icon: Icon plugin
    the Icon plugin to use to render the marker.
draggable: bool, default False
    Set to True to be able to drag the marker around the map.

Returns
-------
Marker names and HTML in obj.template_vars

Examples
--------
>>> Marker(location=[45.5, -122.3], popup='Portland, OR')
>>> Marker(location=[45.5, -122.3], popup=Popup('Portland, OR'))
# If the popup label has characters that need to be escaped in HTML
>>> Marker(location=[45.5, -122.3],
...        popup=Popup('Mom & Pop Arrow Shop >>', parse_html=True))
File:           c:\users\miguel angel\appdata\local\programs\python\python37\lib\site-packages\folium\map.py
Type:           type
Subclasses:     Circle, CircleMarker, RegularPolygonMarker, BoatMarker, SemiCircle

In [11]:
# address_latlng

In [30]:
# geocode address and place marker on map



# get location information for address.
building = 'Zaragoza'
address = geocoder.osm(building)
# address = geocoder.osm('Madrid, Calle Juan de Mena, 14')
# address = geocoder.osm('Madrid, Hospital Ramon y Cajal')

# address = geocoder.osm('Madrid, The Bridge')
# address latitude and longitude
address_latlng = [address.lat, address.lng]

# map
map_madrid = folium.Map(location=[address.lat, address.lng], zoom_start=13)

# add marker to map
folium.Marker(address_latlng,
             popup = building,
             tooltip = 'click').add_to(map_madrid)

# display map
display(map_madrid)

In [27]:
# airports dataframe using vega_datasets
airports = vds.airports()
airports = airports[:25]
airports.head()

,iata,name,city,state,country,latitude,longitude
0,00M,Thigpen,Bay Springs,MS,USA,31.953765,-89.234505
1,00R,Livingston Municipal,Livingston,TX,USA,30.685861,-95.017928
2,00V,Meadow Lake,Colorado Springs,CO,USA,38.945749,-104.569893
3,01G,Perry-Warsaw,Perry,NY,USA,42.741347,-78.052081
4,01J,Hilliard Airpark,Hilliard,FL,USA,30.688012,-81.905944

In [32]:
# multiple markers using dataframe
# there is an example below using apply function instead of loop

# create map
map_airports = folium.Map(location=[38, -98], zoom_start=4)

# plot airport locations
for (index, row) in airports.iterrows():
    folium.Marker(location = [row.loc['latitude'], row.loc['longitude']],
                 popup = row.loc['name'] + ' ' + row['city'],
                 tooltip = 'click').add_to(map_airports)

    
# display map    
map_airports

In [33]:
# markers with apply function

# map
map_airports2 = folium.Map(location=[38, -98], zoom_start=4)

# plot airport locations using apply
airports.apply(lambda row: folium.Marker(location = [row['latitude'], row['longitude']], popup = row.loc['name'] + ' ' + row['city'],).add_to(map_airports2), axis=1)

# display map
map_airports2

In [35]:
markers_dict = {'Los Angeles': [34.041008, -118.246653], 
                'Las Vegas': [36.169726, -115.143996], 
                'Denver': [39.739448, -104.992450], 
                'Chicago': [41.878765, -87.643267], 
                'Manhattan': [40.782949, -73.969559]}

In [18]:
for elemento in markers_dict.items():
    print(elemento[0])
    print(elemento[1])

Los Angeles
[34.041008, -118.246653]
Las Vegas
[36.169726, -115.143996]
Denver
[39.739448, -104.99245]
Chicago
[41.878765, -87.643267]
Manhattan
[40.782949, -73.969559]

In [36]:
# multiple markers using dictionary

markers_dict = {'Los Angeles': [34.041008, -118.246653], 
                'Las Vegas': [36.169726, -115.143996], 
                'Denver': [39.739448, -104.992450], 
                'Chicago': [41.878765, -87.643267], 
                'Manhattan': [40.782949, -73.969559]}

# create map
map_cities = folium.Map(location=[41, -99], zoom_start=4)

# plot locations
for i in markers_dict.items():
    folium.Marker(location=i[1], popup=i[0]).add_to(map_cities)
    print(i)

# display map    
map_cities

('Los Angeles', [34.041008, -118.246653])
('Las Vegas', [36.169726, -115.143996])
('Denver', [39.739448, -104.99245])
('Chicago', [41.878765, -87.643267])
('Manhattan', [40.782949, -73.969559])

# Custom Markers

In [37]:
folium.Icon?

Init signature:
folium.Icon(
    color='blue',
    icon_color='white',
    icon='info-sign',
    angle=0,
    prefix='glyphicon',
    **kwargs,
)
Docstring:
Creates an Icon object that will be rendered
using Leaflet.awesome-markers.

Parameters
----------
color : str, default 'blue'
    The color of the marker. You can use:

        ['red', 'blue', 'green', 'purple', 'orange', 'darkred',
         'lightred', 'beige', 'darkblue', 'darkgreen', 'cadetblue',
         'darkpurple', 'white', 'pink', 'lightblue', 'lightgreen',
         'gray', 'black', 'lightgray']

icon_color : str, default 'white'
    The color of the drawing on the marker. You can use colors above,
    or an html color code.
icon : str, default 'info-sign'
    The name of the marker sign.
    See Font-Awesome website to choose yours.
    Warning : depending on the icon you choose you may need to adapt
    the `prefix` as well.
angle : int, default 0
    The icon will be rotated by this amount of degrees.
prefix : str, default 'glyphicon'
    The prefix states the source of the icon. 'fa' for font-awesome or
    'glyphicon' for bootstrap 3.

https://github.com/lvoogdt/Leaflet.awesome-markers
File:           c:\users\miguel angel\appdata\local\programs\python\python37\lib\site-packages\folium\map.py
Type:           type
Subclasses:     CustomIcon

In [21]:
# map
map_cm_fa = folium.Map(location=[38, -98], zoom_start=4)

'''
Iconos 'fa'
Iconos 'glyphicon'
'''
# add custom marker to map
folium.Marker(location=[38, -98], 
              popup='popup', 
              icon=folium.Icon(color='green', icon='bolt', prefix='fa')).add_to(map_cm_fa)

# display map
map_cm_fa

In [38]:
# search for 'glyphicon bootstrap' icons to see examples

# map
map_cm_glyphicon = folium.Map(location=[38, -98], zoom_start=4)

# add custom marker to map
folium.Marker(location=[38, -98], 
              popup='popup', 
              icon=folium.Icon(icon='glyphicon-plane', prefix='glyphicon')).add_to(map_cm_glyphicon)

# display map
map_cm_glyphicon

In [39]:
# multiple custom markers

# dataframe with custom marker names
cm_df = pd.DataFrame({'city': ['Los Angeles', 'Las Vegas', 'Denver', 'Chicago', 'Manhattan'],
                      'latitude': [34.041008, 36.169726, 39.739448, 41.878765, 40.782949],
                      'longitude': [-118.246653, -115.143996, -104.992450, -87.643267, -73.969559],
                      'icon': ['bicycle', 'car', 'bus', 'truck', 'motorcycle']})
cm_df

          city   latitude   longitude        icon
0  Los Angeles  34.041008 -118.246653     bicycle
1    Las Vegas  36.169726 -115.143996         car
2       Denver  39.739448 -104.992450         bus
3      Chicago  41.878765  -87.643267       truck
4    Manhattan  40.782949  -73.969559  motorcycle

In [40]:
# map
map_cm_multiple = folium.Map(location=[38, -98], zoom_start=4)

# add markers to map
# for loop with itertuples (experiment that appears to work well)
# can also use iterrows or dataframe apply

for i in cm_df.itertuples():
    folium.Marker(location=[i.latitude, i.longitude], 
                  popup=i.city,
                  icon=folium.Icon(icon=i.icon, prefix='fa')).add_to(map_cm_multiple)

# display map    
map_cm_multiple

In [25]:
# cm_enum_df.head()

In [42]:
# enumerate markers

# data
cm_enum_df = pd.DataFrame({'city': ['Los Angeles', 'Las Vegas', 'Denver', 'Chicago', 'Manhattan'],
                           'latitude': [34.041008, 36.169726, 39.739448, 41.878765, 40.782949],
                           'longitude': [-118.246653, -115.143996, -104.992450, -87.643267, -73.969559],
                           'icon_num': [1, 2, 3, 4, 5]})

# map
map_enum_icons = folium.Map([38, -98], zoom_start=4)

# icons using plugins.BeautifyIcon
for i in cm_enum_df.itertuples():
    folium.Marker(location=[i.latitude, i.longitude],
                  popup=i.city,
                  icon=plugins.BeautifyIcon(number=i.icon_num,
                                            border_color='blue',
                                            border_width=1,
                                            text_color='red',
                                            inner_icon_style='margin-top:0px;')).add_to(map_enum_icons)

# display map    
map_enum_icons

# Circle Markers

In [43]:
# map
map_circle = folium.Map(location=[38, -98], zoom_start=4)

# radius of the circle in meters
folium.Circle(radius = 100000, location = [38, -98], color = 'green').add_to(map_circle)

# circle of a fixed size with radius specified in pixels
folium.CircleMarker(location=[39, -105], radius = 25, color = 'blue', fill_color = 'yellow').add_to(map_circle)

# display map
map_circle

# Plot Route

In [28]:
# route

# map
map_plot_route = folium.Map(location=[38, -98], zoom_start=4)

# route_locs = ['Los Angeles', 'Las Vegas', 'Denver', 'Chicago', 'Manhattan']
# can use list of lists or list of tuples
route_lats_longs = [[34.041008,-118.246653],
                    [36.169726,-115.143996], 
                    [39.739448,-104.992450], 
                    [41.878765,-87.643267], 
                    [40.782949,-73.969559]]

# add route to map
folium.PolyLine(route_lats_longs).add_to(map_plot_route)

# display map
map_plot_route

In [29]:
# ant path route
# uses import - from folium import plugins

# map
map_ant_route = folium.Map(location=[38, -98], zoom_start=4)

# add ant path route to map
plugins.AntPath(route_lats_longs).add_to(map_ant_route)

# display map
map_ant_route

# Overlay GeoJSON Layers

In [46]:
# use a link or file
# use geojson.io to create custom geojson files
# can also use folium Draw control to create geojson files (example below)
# convert shapefiles to geojson using QGIS

# map
map_geojson = folium.Map(location=[39.77, -86.15], zoom_start=7)

# add geojson file to map
folium.GeoJson('indiana_outline_map.geojson', name='geojson indiana').add_to(map_geojson)

# # add layer control to map (allows layer to be turned on or off)
folium.LayerControl().add_to(map_geojson)

# display map
map_geojson

# Subgroups with GeoJSON

In [47]:
# map
map_with_subgroups = folium.Map(location=[39.77, -86.15], zoom_start=7)

# all subgroups
all_subgroups = folium.FeatureGroup(name='all sales regions')
map_with_subgroups.add_child(all_subgroups)

# subgroup 1
sales_region1 = plugins.FeatureGroupSubGroup(all_subgroups, 'sales region 1')
map_with_subgroups.add_child(sales_region1)

# subgroup 2
sales_region2 = plugins.FeatureGroupSubGroup(all_subgroups, 'sales region 2')
map_with_subgroups.add_child(sales_region2)

# subgroup 3
sales_region3 = plugins.FeatureGroupSubGroup(all_subgroups, 'sales region 3')
map_with_subgroups.add_child(sales_region3)

# pull in geojson layers and add to map
folium.GeoJson('sales_region1.geojson').add_to(sales_region1)
folium.GeoJson('sales_region2.geojson').add_to(sales_region2)
folium.GeoJson('sales_region3.geojson').add_to(sales_region3)

# add layer control to map (allows layers to be turned on or off)
folium.LayerControl(collapsed=False).add_to(map_with_subgroups)

# display map
map_with_subgroups

# Choropleth Map

In [49]:
folium.Choropleth?

Init signature:
folium.Choropleth(
    geo_data,
    data=None,
    columns=None,
    key_on=None,
    bins=6,
    fill_color=None,
    nan_fill_color='black',
    fill_opacity=0.6,
    nan_fill_opacity=None,
    line_color='black',
    line_weight=1,
    line_opacity=1,
    name=None,
    legend_name='',
    overlay=True,
    control=True,
    show=True,
    topojson=None,
    smooth_factor=None,
    highlight=None,
    **kwargs,
)
Docstring:
Apply a GeoJSON overlay to the map.

Plot a GeoJSON overlay on the base map. There is no requirement
to bind data (passing just a GeoJSON plots a single-color overlay),
but there is a data binding option to map your columnar data to
different feature objects with a color scale.

If data is passed as a Pandas DataFrame, the "columns" and "key-on"
keywords must be included, the first to indicate which DataFrame
columns to use, the second to indicate the layer in the GeoJSON
on which to key the data. The 'columns' keyword does not need to be
passed for a Pandas series.

Colors are generated from color brewer (http://colorbrewer2.org/)
sequential palettes. By default, linear binning is used between
the min and the max of the values. Custom binning can be achieved
with the `bins` parameter.

TopoJSONs can be passed as "geo_data", but the "topojson" keyword must
also be passed with the reference to the topojson objects to convert.
See the topojson.feature method in the TopoJSON API reference:
https://github.com/topojson/topojson/wiki/API-Reference


Parameters
----------
geo_data: string/object
    URL, file path, or data (json, dict, geopandas, etc) to your GeoJSON
    geometries
data: Pandas DataFrame or Series, default None
    Data to bind to the GeoJSON.
columns: dict or tuple, default None
    If the data is a Pandas DataFrame, the columns of data to be bound.
    Must pass column 1 as the key, and column 2 the values.
key_on: string, default None
    Variable in the `geo_data` GeoJSON file to bind the data to. Must
    start with 'feature' and be in JavaScript objection notation.
    Ex: 'feature.id' or 'feature.properties.statename'.
bins: int or sequence of scalars or str, default 6
    If `bins` is an int, it defines the number of equal-width
    bins between the min and the max of the values.
    If `bins` is a sequence, it directly defines the bin edges.
    For more information on this parameter, have a look at
    numpy.histogram function.
fill_color: string, optional
    Area fill color, defaults to blue. Can pass a hex code, color name,
    or if you are binding data, one of the following color brewer palettes:
    'BuGn', 'BuPu', 'GnBu', 'OrRd', 'PuBu', 'PuBuGn', 'PuRd', 'RdPu',
    'YlGn', 'YlGnBu', 'YlOrBr', and 'YlOrRd'.
nan_fill_color: string, default 'black'
    Area fill color for nan or missing values.
    Can pass a hex code, color name.
fill_opacity: float, default 0.6
    Area fill opacity, range 0-1.
nan_fill_opacity: float, default fill_opacity
    Area fill opacity for nan or missing values, range 0-1.
line_color: string, default 'black'
    GeoJSON geopath line color.
line_weight: int, default 1
    GeoJSON geopath line weight.
line_opacity: float, default 1
    GeoJSON geopath line opacity, range 0-1.
legend_name: string, default empty string
    Title for data legend.
topojson: string, default None
    If using a TopoJSON, passing "objects.yourfeature" to the topojson
    keyword argument will enable conversion to GeoJSON.
smooth_factor: float, default None
    How much to simplify the polyline on each zoom level. More means
    better performance and smoother look, and less means more accurate
    representation. Leaflet defaults to 1.0.
highlight: boolean, default False
    Enable highlight functionality when hovering over a GeoJSON area.
name : string, optional
    The name of the layer, as it will appear in LayerControls
overlay : bool, default True
    Adds the layer as an optional overlay (True) or the base layer (False).
control : bool, default True
    Whether the Layer will be included in LayerControls.
show: bool, default True
    Whether the layer will be shown on opening (only for overlays).

Returns
-------
GeoJSON data layer in obj.template_vars

Examples
--------
>>> Choropleth(geo_data='us-states.json', line_color='blue',
...            line_weight=3)
>>> Choropleth(geo_data='geo.json', data=df,
...            columns=['Data 1', 'Data 2'],
...            key_on='feature.properties.myvalue',
...            fill_color='PuBu',
...            bins=[0, 20, 30, 40, 50, 60])
>>> Choropleth(geo_data='countries.json',
...            topojson='objects.countries')
>>> Choropleth(geo_data='geo.json', data=df,
...            columns=['Data 1', 'Data 2'],
...            key_on='feature.properties.myvalue',
...            fill_color='PuBu',
...            bins=[0, 20, 30, 40, 50, 60],
...            highlight=True)
File:           c:\users\miguel angel\appdata\local\programs\python\python37\lib\site-packages\folium\features.py
Type:           type
Subclasses:

In [33]:
import json

# load geo_json
# shapefiles can be converted to geojson with QGIS
with open('geojson_indiana_counties.geojson') as f:
    geo_json_counties = json.load(f)
    
for i in geo_json_counties['features']:
    i['id'] = i['properties']['NAME_L']

In [34]:
i

{'type': 'Feature',
 'properties': {'AREA': 611358389.42969,
  'PERIMETER': 133816.83216,
  'NAME_U': 'VANDERBURGH',
  'NAME_L': 'Vanderburgh',
  'NCAPC': 82,
  'CNTY_FIPS': '163',
  'STFID': '18163',
  'POP2000': 171922,
  'WHITE': 153519,
  'BLACK': 14078,
  'AMERI_ES': 305,
  'ASIAN': 1296,
  'HAWN_PI': 70,
  'OTHER': 685,
  'MULT_RACE': 1969,
  'HISPANIC': 1679,
  'MALES': 81509,
  'FEMALES': 90413,
  'AGE_UNDER5': 10688,
  'AGE_5_17': 29091,
  'AGE_18_21': 12606,
  'AGE_22_29': 18189,
  'AGE_30_39': 23571,
  'AGE_40_49': 26112,
  'AGE_50_64': 25337,
  'AGE_65_UP': 26328,
  'MED_AGE': 36.9,
  'MED_AGE_M': 35.5,
  'MED_AGE_F': 38.2,
  'HOUSEHOLDS': 70623,
  'AVE_HH_SZ': 2.33,
  'HSEHLD_1_M': 8962,
  'HSEHLD_1_F': 12914,
  'MARHH_CHD': 13788,
  'MARHH_NO_C': 19775,
  'MHH_CHILD': 1299,
  'FHH_CHILD': 5157,
  'FAMILIES': 44442,
  'AVE_FAM_SZ': 2.93,
  'HSE_UNITS': 76300,
  'VACANT': 5677,
  'OWNER_OCC': 47184,
  'RENTER_OCC': 23439},
 'geometry': {'type': 'MultiPolygon',
  'coordinates': [[[[-87.68841523590109, 38.16849463277905],
     [-87.67084249466355, 38.16835750096614],
     [-87.65244942045554, 38.168154705764685],
     [-87.63368054558079, 38.167883463660814],
     [-87.61494929452878, 38.16753241762063],
     [-87.59665135855919, 38.16749612694952],
     [-87.57811906819924, 38.1675077077548],
     [-87.57811722251293, 38.167003014970454],
     [-87.55965779383544, 38.16673193434511],
     [-87.54103130087383, 38.16667051615262],
     [-87.52264175810461, 38.1662175492022],
     [-87.50428082455316, 38.16584719826095],
     [-87.48581520713813, 38.16569521697867],
     [-87.46727500557137, 38.16547303433321],
     [-87.4675563862636, 38.15088053903292],
     [-87.46755583969835, 38.15079492154297],
     [-87.46782090293179, 38.13639622581275],
     [-87.46782001112764, 38.13625653377789],
     [-87.46815557145437, 38.12179893915505],
     [-87.47213949529218, 38.121823553019944],
     [-87.47217100598118, 38.10722743898748],
     [-87.47259593439087, 38.09284601173118],
     [-87.47274279834184, 38.078353008325365],
     [-87.47300516102999, 38.063931606381374],
     [-87.47300728559267, 38.06381893873747],
     [-87.47306221494928, 38.04949747613473],
     [-87.4733470246703, 38.03487312567315],
     [-87.4502256991557, 38.03496394085049],
     [-87.45009914025573, 38.02044932741357],
     [-87.45006934314571, 38.005970359025355],
     [-87.45013648573158, 37.99121609232303],
     [-87.45024614581337, 37.97672299919896],
     [-87.45049337594597, 37.962098656876144],
     [-87.45073956396202, 37.94778072104982],
     [-87.45083571865828, 37.94110628780292],
     [-87.45144677393178, 37.94082454436371],
     [-87.45212730817872, 37.94050647910851],
     [-87.45293178671395, 37.940160894112005],
     [-87.45361252552404, 37.939820287167265],
     [-87.45466449752799, 37.939356567952],
     [-87.45559220326007, 37.93887078822826],
     [-87.45647071574204, 37.93842575018682],
     [-87.45726231337304, 37.9380170950645],
     [-87.45821496241636, 37.93754471709156],
     [-87.45858631717473, 37.93738554421668],
     [-87.45889568054191, 37.93720858609539],
     [-87.4592047989505, 37.93704965396605],
     [-87.4596007336094, 37.93684081087118],
     [-87.46004598430667, 37.93661374779233],
     [-87.46035023154022, 37.936472857546846],
     [-87.46076963038392, 37.93626391871484],
     [-87.46114689555334, 37.93602810473648],
     [-87.46186437244474, 37.93566026724276],
     [-87.46255720364944, 37.93533308042477],
     [-87.46358663937752, 37.93481078595102],
     [-87.46438769023847, 37.93433444863845],
     [-87.46519434999072, 37.933790486723375],
     [-87.46578531922118, 37.933387073628246],
     [-87.46656224432904, 37.93281167474298],
     [-87.46753050652475, 37.932073277909645],
     [-87.46851329994102, 37.93133030874678],
     [-87.46937776609434, 37.93065990682754],
     [-87.4704149660559, 37.92986713354487],
     [-87.47155254057579, 37.92920463643261],
     [-87.47481436954871, 37.92749258244475],
     [-87.47555303639945, 37.927070498232865],
     [-87.47659126037314, 37.92639934083602],
     [-87.47764135051703, 37.92569658081162],
     [-87.47850610569196, 37.92509370744217],
     [-87.48055679614073, 37.923746929908106],
     [-87.4815325008575, 37.92304443877418],
     [-87.48287793912911, 37.92195737303438],
     [-87.48446996675098, 37.920634940452906],
     [-87.48589901579749, 37.91946187277546],
     [-87.48645515116212, 37.91898639575824],
     [-87.48713506008659, 37.91841126143892],
     [-87.48822131287825, 37.91756404980604],
     [-87.48932034214353, 37.916770852652675],
     [-87.49039476091322, 37.91602281248129],
     [-87.49151835978805, 37.91518893407312],
     [-87.49218453968858, 37.91464537307102],
     [-87.49293036783547, 37.9140519034872],
     [-87.49352368485926, 37.91356722418135],
     [-87.49451100748313, 37.91283303088364],
     [-87.4956840388318, 37.91196285299761],
     [-87.49721598919669, 37.9110235504738],
     [-87.49848912302282, 37.910351206573836],
     [-87.50001106206922, 37.909623714425535],
     [-87.50048001334287, 37.9093693585269],
     [-87.5007145073012, 37.909192608549155],
     [-87.50101109829761, 37.909051645602716],
     [-87.50166720849737, 37.90882352698953],
     [-87.50212484690847, 37.90863230343501],
     [-87.50285417133098, 37.90824613912468],
     [-87.50354665458337, 37.90793223155707],
     [-87.50407865554297, 37.90770012393805],
     [-87.50475927178564, 37.90747188313801],
     [-87.50535354923873, 37.90730259335472],
     [-87.50591083881997, 37.90718303082255],
     [-87.50641877783023, 37.90707269095905],
     [-87.50693915677813, 37.9069622953264],
     [-87.50737232016317, 37.906834247481164],
     [-87.50790473470765, 37.90666521148804],
     [-87.50835005701771, 37.906496549276426],
     [-87.50873343283138, 37.906314633714445],
     [-87.50931540564532, 37.90616790951857],
     [-87.50961265166262, 37.906126064586246],
     [-87.51012110659572, 37.906092316652256],
     [-87.51054338773227, 37.90614005694944],
     [-87.51085391542907, 37.906219826171686],
     [-87.51114010357799, 37.90632673914032],
     [-87.51138937385883, 37.90649239602474],
     [-87.5117920778831, 37.906792579612315],
     [-87.51289807479304, 37.907625969851466],
     [-87.51405789917392, 37.90847714032427],
     [-87.5153546855952, 37.9094403613987],
     [-87.51723750136881, 37.910829108917646],
     [-87.51789831470221, 37.91127685024739],
     [-87.51884531753245, 37.911876546562915],
     [-87.51954296305954, 37.912301583786956],
     [-87.51994151080014, 37.91250712145787],
     [-87.52058902382092, 37.912828725032284],
     [-87.52132322079326, 37.91314092813119],
     [-87.52229331237814, 37.913479118821826],
     [-87.52323820837441, 37.91377234879088],
     [-87.52422069555575, 37.91410145545956],
     [-87.5255634412806, 37.91454611384692],
     [-87.52701793092493, 37.914954204751375],
     [-87.52841090008329, 37.91540761851386],
     [-87.52989916348287, 37.915860586677944],
     [-87.53099705603185, 37.91621164914865],
     [-87.53237801956574, 37.916719147473124],
     [-87.53351081733685, 37.91722324828793],
     [-87.53483015533892, 37.9178076068915],
     [-87.53627408282178, 37.91845897988081],
     [-87.53766855703392, 37.91915111911899],
     [-87.53846673082033, 37.919539532088635],
     [-87.53970421188576, 37.92010167777433],
     [-87.54089927102378, 37.920645979477655],
     [-87.54162112056544, 37.920949098871695],
     [-87.54249250897395, 37.92132813439399],
     [-87.54430968705383, 37.9220948547475],
     [-87.54518051418897, 37.92244232759049],
     [-87.54601496159145, 37.9228215079533],
     [-87.54681209662637, 37.923250426768895],
     [-87.5475342963055, 37.923594066100094],
     [-87.54804505943339, 37.92385756957925],
     [-87.54841979230503, 37.9240450950537],
     [-87.54924054180263, 37.92444234199715],
     [-87.55012443464625, 37.92486632673922],
     [-87.55084702094359, 37.92520994374241],
     [-87.55161982550919, 37.92570654037176],
     [-87.55259237695627, 37.92633288124918],
     [-87.55335298070904, 37.92681149780408],
     [-87.5541501672967, 37.92723585966208],
     [-87.55496029893297, 37.92767818082676],
     [-87.55557030386095, 37.92798624776006],
     [-87.55614396163759, 37.92833053490454],
     [-87.55669295674198, 37.9287515455796],
     [-87.55727963360825, 37.92921743971768],
     [-87.55786648813617, 37.92970586228547],
     [-87.55845387645196, 37.93021681158295],
     [-87.55909054801023, 37.93075456243744],
     [-87.55975285122777, 37.9313417587938],
     [-87.56042694708806, 37.93188833712589],
     [-87.56181344464467, 37.933057908695034],
     [-87.56278480998245, 37.934017646741886],
     [-87.56337131415874, 37.934636729852535],
     [-87.56462820813941, 37.93600517143871],
     [-87.56548010823558, 37.937051082156465],
     [-87.5660690494724, 37.937796320066695],
     [-87.5666244610011, 37.938573261466566],
     [-87.56716731496424, 37.93942687015354],
     [-87.56778170633953, 37.940239573022815],
     [-87.56859605501202, 37.941200018966235],
     [-87.56921138077873, 37.94212987694871],
     [-87.56995278239197, 37.94335654583016],
     [-87.57060692232191, 37.944425907610345],
     [-87.57116043168345, 37.94549575404253],
     [-87.57174579831869, 37.94649784628571],
     [-87.57224967059634, 37.94744625456995],
     [-87.57254131686152, 37.94822444893108],
     [-87.57262795299603, 37.94852595840596],
     [-87.57289888008492, 37.94952056135752],
     [-87.57338409033353, 37.95126669356773],
     [-87.57346049430348, 37.95153220066506],
     [-87.57357340462286, 37.951689375373334],
     [-87.57368568462054, 37.95176543727428],
     [-87.57387244794452, 37.95181409719414],
     [-87.57496431062667, 37.95193494642552],
     [-87.57600008426017, 37.95206957941543],
     [-87.57625507079767, 37.952108888654756],
     [-87.57643593085496, 37.9521755991305],
     [-87.57656571351426, 37.95226058537016],
     [-87.57658615674512, 37.95237314594751],
     [-87.57656366770529, 37.95249943621196],
     [-87.57650617692377, 37.95265293656939],
     [-87.57642926394857, 37.95282455777638],
     [-87.57634787110575, 37.952969162294806],
     [-87.57624755236425, 37.95314991089373],
     [-87.57602077203484, 37.9534890036734],
     [-87.57574219130034, 37.953936503817175],
     [-87.57547957421781, 37.95442448305609],
     [-87.57515586185056, 37.95510653681128],
     [-87.57483249026124, 37.955878716515265],
     [-87.57455564862532, 37.95655152661292],
     [-87.57441885553165, 37.95712000445815],
     [-87.57430759659839, 37.95772440886563],
     [-87.57423805373588, 37.95806723676173],
     [-87.57418390634858, 37.95846857300297],
     [-87.57411038413284, 37.958757343093126],
     [-87.57399000697006, 37.95942488150532],
     [-87.57394876851117, 37.96015963003577],
     [-87.57395609859256, 37.961101437042124],
     [-87.57397676626208, 37.96174575485598],
     [-87.57399715374825, 37.96235402257493],
     [-87.57413681379226, 37.963020291685474],
     [-87.57427841149601, 37.96388934009021],
     [-87.57441857333016, 37.964573631913375],
     [-87.57462682157242, 37.96532068081664],
     [-87.57487043847304, 37.9660405178875],
     [-87.57520519958823, 37.966813985760325],
     [-87.57546613079695, 37.96738051846538],
     [-87.57579511427622, 37.96805036507914],
     [-87.5761362846439, 37.96854890709921],
     [-87.57650386356408, 37.96896620313168],
     [-87.57698090489046, 37.969549698570155],
     [-87.57747055254448, 37.97006102743838],
     [-87.57789236535974, 37.97049607839246],
     [-87.57849067638858, 37.97106995883656],
     [-87.57908789935466, 37.971504142630664],
     [-87.57994189334076, 37.972013666753824],
     [-87.58071488800205, 37.97249203959497],
     [-87.58175280913476, 37.97317639239962],
     [-87.5826132089858, 37.9736362946371],
     [-87.5833993664675, 37.974110077986694],
     [-87.58401930267875, 37.97439541209117],
     [-87.58456445575588, 37.97467210173822],
     [-87.58520130235185, 37.97497987757538],
     [-87.58570198515599, 37.97516665489888],
     [-87.58626806518987, 37.97534409132815],
     [-87.58689160148509, 37.97540857808856],
     [-87.58755317309482, 37.97546836514782],
     [-87.58876836485285, 37.97552537872742],
     [-87.58963188244684, 37.975521053358285],
     [-87.59081953015807, 37.9755150940624],
     [-87.59152076228251, 37.97546199932843],
     [-87.59204712909103, 37.975477376829275],
     [-87.59264149588188, 37.975541979898324],
     [-87.59349131138777, 37.975515163180354],
     [-87.59435423912845, 37.97539363947243],
     [-87.59544542200594, 37.97516280038624],
     [-87.5965079165506, 37.974729308248655],
     [-87.59775819001077, 37.974155153732355],
     [-87.59874805516924, 37.973631882236944],
     [-87.5999477014424, 37.9729182634284],
     [-87.60073058262094, 37.97227886405932],
     [-87.6013101297093, 37.97166303108879],
     [-87.60174692825423, 37.971038912723095],
     [-87.6021703470881, 37.97017151494987],
     [-87.60247500543034, 37.96957510860474],
     [-87.60287635021078, 37.968707821184175],
     [-87.60305969574475, 37.968157099009574],
     [-87.60324237491118, 37.96752526447878],
     [-87.60334055730449, 37.96713270295334],
     [-87.60342250622145, 37.966582500094624],
     [-87.60345083336324, 37.96600102730697],
     [-87.60344434230228, 37.965207931548356],
     [-87.60346352790897, 37.964509338704914],
     [-87.60347576748937, 37.96365756324849],
     [-87.60337419630724, 37.96202676122287],
     [-87.6034069867738, 37.96064312260782],
     [-87.60345655584338, 37.959962399064345],
     [-87.60351828144333, 37.959376247878936],
     [-87.60355899750085, 37.958961448361435],
     [-87.60359960248879, 37.95853313011095],
     [-87.60366248244493, 37.95813173604635],
     [-87.6037811475547, 37.95776610700435],
     [-87.60395281928113, 37.95718389749691],
     [-87.60415648495317, 37.95642577294357],
     [-87.6043175166429, 37.9558481238543],
     [-87.6044577112787, 37.95541929350425],
     [-87.60456539225282, 37.95510329061718],
     [-87.60462926162222, 37.954823564169985],
     [-87.60470491910642, 37.95459334774279],
     [-87.60470255475525, 37.954304948803674],
     [-87.60465408996757, 37.953773439908375],
     [-87.60465043304126, 37.95332732272688],
     [-87.60468077848718, 37.95299369136862],
     [-87.60477750275575, 37.95268675733523],
     [-87.60485102842651, 37.9522402433046],
     [-87.60499036336863, 37.95170776873034],
     [-87.60525061275517, 37.95112960772404],
     [-87.60560992914422, 37.95048784623641],
     [-87.60595778383268, 37.94983712978201],
     [-87.60615922169326, 37.949462058723434],
     [-87.60679707454597, 37.94848087608514],
     [-87.60727727451248, 37.947793421523244],
     [-87.60806564106004, 37.946996218430634],
     [-87.6088331138024, 37.94629825955567],
     [-87.60959004750899, 37.94570399811101],
     [-87.61062131118048, 37.94491002550085],
     [-87.6113119543957, 37.94430257765765],
     [-87.6119047449683, 37.943862372578366],
     [-87.6127007492548, 37.94326788784709],
     [-87.61407827606313, 37.94233688830692],
     [-87.6154068790043, 37.94142866066043],
     [-87.61601856261116, 37.94095679096605],
     [-87.61643828375529, 37.940666181185904],
     [-87.61722905463957, 37.94013478319836],
     [-87.61809628861651, 37.93956242036074],
     [-87.61866725439424, 37.9391583472246],
     [-87.6190621904419, 37.93884081978762],
     [-87.61951596619336, 37.938500449077274],
     [-87.61979025891917, 37.93830072156254],
     [-87.62009290054546, 37.93804676682202],
     [-87.62049809937272, 37.93772467402962],
     [-87.62102344385193, 37.93731181713095],
     [-87.62146704028372, 37.936989518327806],
     [-87.62188506711942, 37.9366718594225],
     [-87.62210681714521, 37.936526481373306],
     [-87.62225237707766, 37.93641305087479],
     [-87.62233462523353, 37.93634051296469],
     [-87.62240457905806, 37.93628606576223],
     [-87.62243367624927, 37.93623634108064],
     [-87.62240389506792, 37.936204953578056],
     [-87.6223288625189, 37.9362053504397],
     [-87.6222266003754, 37.93622391698093],
     [-87.62208591908772, 37.93628324445598],
     [-87.62188185001689, 37.936374451824],
     [-87.62144300025521, 37.93658406630283],
     [-87.62100686472766, 37.93682070342106],
     [-87.62070220246655, 37.937002568264624],
     [-87.62037869140373, 37.93718453169774],
     [-87.62004336788762, 37.93735754362135],
     [-87.6198696108837, 37.93741704273647],
     [-87.61949687026457, 37.93758123734607],
     [-87.61919498576356, 37.937713512899485],
     [-87.61891641945216, 37.93782763929704],
     [-87.61854853989728, 37.93797828603736],
     [-87.61824242242906, 37.93811508783399],
     [-87.61801032540986, 37.93821544862033],
     [-87.61785928633589, 37.938270319014826],
     [-87.61773519834264, 37.938316034861806],
     [-87.6176112395513, 37.93833471130275],
     [-87.61754874297124, 37.9383034942926],
     [-87.61749745389515, 37.93820912837197],
     [-87.61749244877234, 37.93807846808003],
     [-87.61751777876616, 37.93787554565681],
     [-87.61753552766612, 37.93765914370883],
     [-87.61758417690206, 37.93743807313749],
     [-87.6176480201573, 37.93716284557949],
     [-87.6177344117485, 37.936819903092804],
     [-87.61774832355916, 37.93661253408965],
     [-87.61777335066577, 37.93637356168107],
     [-87.61782139488169, 37.93608039119337],
     [-87.61786236990214, 37.93587738648709],
     [-87.61791345246554, 37.93569235442212],
     [-87.61807704427252, 37.93535351261665],
     [-87.61831495863196, 37.934802477589564],
     [-87.61851934273291, 37.9344093435462],
     [-87.61878054420168, 37.93400689749036],
     [-87.61896413940234, 37.93372202642352],
     [-87.61921265521605, 37.933418787704944],
     [-87.61947840381569, 37.93309292554986],
     [-87.61983894075307, 37.932748537773605],
     [-87.61983811606295, 37.93273502280776],
     [-87.62026204929539, 37.9323181967773],
     [-87.62057251719615, 37.931983083516954],
     [-87.62082619388035, 37.931576166069526],
     [-87.62106337383827, 37.93111075143702],
     [-87.62122056945448, 37.930690822960095],
     [-87.62141682920239, 37.93018055919969],
     [-87.62157417265414, 37.92977865517184],
     [-87.6217211493111, 37.92907487427674],
     [-87.62186989323672, 37.92862344439392],
     [-87.62208379014045, 37.92826630511871],
     [-87.62225659470357, 37.92780122818245],
     [-87.6224233222406, 37.92754347935267],
     [-87.62261827642524, 37.92734416466022],
     [-87.62282571220196, 37.92714929002153],
     [-87.62307323578703, 37.926985747847866],
     [-87.62338507644868, 37.92681735801542],
     [-87.62370547418224, 37.92669398640777],
     [-87.62397751495011, 37.92657087034881],
     [-87.6242575802277, 37.92642968533119],
     [-87.62446198709775, 37.926297914037725],
     [-87.62474461555328, 37.92616572714076],
     [-87.62502696372644, 37.926042553935474],
     [-87.62517561019561, 37.925960648398515],
     [-87.62533195196326, 37.925905740425975],
     [-87.62556345623751, 37.92590901644297],
     [-87.62573498634868, 37.92592613024498],
     [-87.62590717768416, 37.92597929180381],
     [-87.62604984649558, 37.926073168137464],
     [-87.62626025082622, 37.92622977400199],
     [-87.62652359977065, 37.926507771494435],
     [-87.62667503750065, 37.9267548193221],
     [-87.6268851865013, 37.92713224093514],
     [-87.6269951073719, 37.92751470265187],
     [-87.62703875251631, 37.92783893370275],
     [-87.62705288613206, 37.92816332197881],
     [-87.62705648375037, 37.92858690802161],
     [-87.62705601213815, 37.92886630970142],
     [-87.6270912839221, 37.92904187282469],
     [-87.62713956993403, 37.92915878288234],
     [-87.62723649272971, 37.929266420805014],
     [-87.62737088753562, 37.92930626230759],
     [-87.62750529334365, 37.92930554565858],
     [-87.62765271280738, 37.92924617575532],
     [-87.62779240752728, 37.92911474387612],
     [-87.62790272575808, 37.9289158720166],

In [35]:
geo_json_counties['features'][0]

{'type': 'Feature',
 'properties': {'AREA': 835203110.44822,
  'PERIMETER': 116410.31836,
  'NAME_U': 'STEUBEN',
  'NAME_L': 'Steuben',
  'NCAPC': 76,
  'CNTY_FIPS': '151',
  'STFID': '18151',
  'POP2000': 33214,
  'WHITE': 32281,
  'BLACK': 123,
  'AMERI_ES': 109,
  'ASIAN': 133,
  'HAWN_PI': 6,
  'OTHER': 283,
  'MULT_RACE': 279,
  'HISPANIC': 683,
  'MALES': 16771,
  'FEMALES': 16443,
  'AGE_UNDER5': 2199,
  'AGE_5_17': 6322,
  'AGE_18_21': 2241,
  'AGE_22_29': 3307,
  'AGE_30_39': 4832,
  'AGE_40_49': 4966,
  'AGE_50_64': 5411,
  'AGE_65_UP': 3936,
  'MED_AGE': 35.5,
  'MED_AGE_M': 34.2,
  'MED_AGE_F': 36.9,
  'HOUSEHOLDS': 12738,
  'AVE_HH_SZ': 2.53,
  'HSEHLD_1_M': 1462,
  'HSEHLD_1_F': 1634,
  'MARHH_CHD': 3057,
  'MARHH_NO_C': 4208,
  'MHH_CHILD': 375,
  'FHH_CHILD': 715,
  'FAMILIES': 8911,
  'AVE_FAM_SZ': 3.0,
  'HSE_UNITS': 17337,
  'VACANT': 4599,
  'OWNER_OCC': 9951,
  'RENTER_OCC': 2787},
 'geometry': {'type': 'MultiPolygon',
  'coordinates': [[[[-84.84040837705693, 41.76011016200025],
     [-84.82062359974854, 41.76012913319963],
     [-84.80589099334868, 41.76022202910006],
     [-84.80595515840467, 41.74614884711497],
     [-84.80586763201916, 41.731861282632806],
     [-84.80589267390825, 41.71733315282286],
     [-84.8059238675704, 41.70267820921448],
     [-84.80603515837093, 41.68911792447783],
     [-84.80576220029766, 41.674629561305316],
     [-84.80590468772353, 41.66013711619026],
     [-84.80582883372782, 41.645585243860936],
     [-84.80581315274839, 41.63087475925605],
     [-84.80576490756772, 41.616424657538595],
     [-84.8056731994117, 41.60306099684162],
     [-84.80545307846222, 41.588439143039224],
     [-84.80527021428361, 41.57403023380309],
     [-84.80504623476858, 41.55950659080435],
     [-84.80482231651683, 41.54488839021763],
     [-84.80468831057769, 41.53038922506556],
     [-84.81555347643034, 41.53021982680466],
     [-84.81582948935038, 41.53021511790483],
     [-84.83496889257377, 41.52988697160216],
     [-84.83511362564094, 41.52988426018662],
     [-84.8544164244523, 41.529521006609244],
     [-84.8736851703785, 41.52923843374432],
     [-84.87378533073733, 41.52923583188195],
     [-84.89291401900871, 41.52889782097314],
     [-84.89332521003125, 41.528871607788865],
     [-84.91213144741275, 41.528491759432264],
     [-84.91247885970344, 41.528487503674896],
     [-84.93139554441086, 41.52836718966407],
     [-84.95039351212307, 41.52824761985156],
     [-84.95112648710544, 41.528238937238825],
     [-84.96858054494348, 41.52805292486294],
     [-84.98678397563644, 41.527769270715446],
     [-84.98785026210001, 41.5277654763586],
     [-85.00607466792744, 41.52751478170772],
     [-85.00733531655725, 41.52750600650865],
     [-85.0264813769742, 41.52737103286434],
     [-85.02668198286706, 41.52736919234365],
     [-85.04608302191521, 41.527189535938184],
     [-85.06438049106477, 41.527058988533746],
     [-85.06558618215549, 41.527056092247484],
     [-85.08079132149267, 41.526983357473476],
     [-85.10015971788698, 41.526912954772236],
     [-85.11915792463786, 41.52683795766623],
     [-85.11978438841913, 41.52683888257856],
     [-85.13877287556775, 41.52684343836893],
     [-85.1391303159508, 41.5268324515381],
     [-85.15849886660476, 41.526683554877344],
     [-85.17666090495806, 41.52662137691867],
     [-85.17773438090047, 41.52660713600863],
     [-85.19408903529573, 41.52665353958099],
     [-85.1941577231239, 41.54126116088201],
     [-85.19408396518115, 41.55572241303517],
     [-85.19429693776068, 41.57034134087008],
     [-85.19433984552619, 41.584827485262416],
     [-85.19431766020713, 41.59951634259151],
     [-85.19445870699234, 41.612819916952304],
     [-85.19452884881498, 41.62737478380517],
     [-85.19468463851244, 41.64191717248334],
     [-85.19488951578901, 41.65653447292],
     [-85.19506594613651, 41.67121726986853],
     [-85.1952544841797, 41.685720914887746],
     [-85.19554651791476, 41.700347449169776],
     [-85.19581958380415, 41.714856818070174],
     [-85.19595643841821, 41.729177880918634],
     [-85.19629063344189, 41.74381132160469],
     [-85.19628540719546, 41.7439980006153],
     [-85.19666105237279, 41.758310257241504],
     [-85.19665677041617, 41.75841776041912],
     [-85.19665139967695, 41.759739016774176],
     [-85.18143971876968, 41.759694454781105],
     [-85.16220165605445, 41.759628421263436],
     [-85.14269731778886, 41.75967944583946],
     [-85.1233125612812, 41.75973787306263],
     [-85.10344356794106, 41.75973899196434],
     [-85.08433398836658, 41.759741223041175],
     [-85.06804095678694, 41.7596899743425],
     [-85.04886955363729, 41.75974768321632],
     [-85.02938178649781, 41.759841252304454],
     [-85.01021248070256, 41.759787783825026],
     [-84.9911770251325, 41.75959510537701],
     [-84.97190564977511, 41.75958646843862],
     [-84.95735820115608, 41.759628510779734],
     [-84.93792146867244, 41.759726486614625],
     [-84.91741773173253, 41.75982856922812],
     [-84.897862511144, 41.75989355519801],
     [-84.87940151683078, 41.75992592519495],
     [-84.860089289424, 41.76003964111984],
     [-84.84040837705693, 41.76011016200025]]]]},
 'id': 'Steuben'}

In [48]:
pop_df = pd.read_csv('indiana_population_by_county.csv')
pop_df[pop_df['County'] == 'Steuben']
pop_df

         County    State  Population
0         Adams  Indiana       35636
1         Allen  Indiana      375351
2   Bartholomew  Indiana       82753
3        Benton  Indiana        8653
4     Blackford  Indiana       11930
..          ...      ...         ...
87   Washington  Indiana       27943
88        Wayne  Indiana       65936
89        Wells  Indiana       28206
90        White  Indiana       24133
91      Whitley  Indiana       34074

[92 rows x 3 columns]

In [37]:
# more examples for choropleth maps in the documentation

import json

# load geo_json
# shapefiles can be converted to geojson with QGIS
with open('geojson_indiana_counties.geojson') as f:
    geo_json_counties = json.load(f)
    
# add feature 'id' county name to geojson
# access features
for i in geo_json_counties['features']:
    i['id'] = i['properties']['NAME_L']
    
# load data associated with geo_json
pop_df = pd.read_csv('indiana_population_by_county.csv')

# map    
map_choropleth = folium.Map(location=[39.77, -86.15], zoom_start=7)

# choropleth
folium.Choropleth(
    geo_data=geo_json_counties,
    name='choropleth',
    data=pop_df,
    columns=['County', 'Population'],
    # see folium.Choropleth? for details on key_on
    key_on='feature.id',
    fill_color='YlGn',
    fill_opacity=0.5,
    line_opacity=0.5,
    legend_name='Population',
    highlight=True
).add_to(map_choropleth)

# layer control to turn choropleth on or off
folium.LayerControl().add_to(map_choropleth)

# display map
map_choropleth

# Heat Map

In [50]:
# use import geocoder

# get location data for large cities (latitude and longitude)
new_york_city = geocoder.osm('New York City, New York')
los_angeles = geocoder.osm('Los Angeles, California')
chicago = geocoder.osm('Chicago, Illinois')
houston = geocoder.osm('Houston, Texas')
phoenix = geocoder.osm('Phoenix, Arizona')
philadelphia = geocoder.osm('Philadelphia, Pennsylvania')
san_antonio = geocoder.osm('San Antonio, Texas')
san_diego = geocoder.osm('San Diego, California')
dallas = geocoder.osm('Dallas, Texas')
san_jose = geocoder.osm('San Jose, California')

# create latitude, longitude, intensity for heat map
# intensity is population scaled down so heat dots are more readable
new_york_city_latlng = [new_york_city.lat, new_york_city.lng, 8398748/1000]
los_angeles_latlng = [los_angeles.lat, los_angeles.lng, 3990456/1000]
chicago_latlng = [chicago.lat, chicago.lng, 2705994/1000]
houston_latlng = [houston.lat, houston.lng, 2325502/1000]
phoenix_latlng = [phoenix.lat, phoenix.lng, 1660272/1000]
philadelphia_latlng = [philadelphia.lat, philadelphia.lng, 1584138/1000]
san_antonio_latlng = [san_antonio.lat, san_antonio.lng, 1532233/1000]
san_diego_latlng = [san_diego.lat, san_diego.lng, 1425976/1000]
dallas_latlng = [dallas.lat, dallas.lng, 1345047/1000]
san_jose_latlng = [san_jose.lat, san_jose.lng, 1030119/1000]

# create list of cities with latitude, longitude, intensity
large_cities = [new_york_city_latlng, los_angeles_latlng, chicago_latlng, houston_latlng, phoenix_latlng, 
                philadelphia_latlng, san_antonio_latlng, san_diego_latlng, dallas_latlng, san_jose_latlng]

map_heatmap = folium.Map([40, -99], tiles='CartoDB Positron', zoom_start=4)

plugins.HeatMap(large_cities).add_to(map_heatmap)

map_heatmap

In [76]:
plugins.HeatMapWithTime?

Init signature:
plugins.HeatMapWithTime(
    data,
    index=None,
    name=None,
    radius=15,
    min_opacity=0,
    max_opacity=0.6,
    scale_radius=False,
    gradient=None,
    use_local_extrema=False,
    auto_play=False,
    display_index=True,
    index_steps=1,
    min_speed=0.1,
    max_speed=10,
    speed_step=0.1,
    position='bottomleft',
    overlay=True,
    control=True,
    show=True,
)
Docstring:
Create a HeatMapWithTime layer

Parameters
----------
data: list of list of points of the form [lat, lng] or [lat, lng, weight]
    The points you want to plot. The outer list corresponds to the various time
    steps in sequential order. (weight is in (0, 1] range and defaults to 1 if
    not specified for a point)
index: Index giving the label (or timestamp) of the elements of data. Should have
    the same length as data, or is replaced by a simple count if not specified.
name : string, default None
    The name of the Layer, as it will appear in LayerControls.
radius: default 15.
    The radius used around points for the heatmap.
min_opacity: default 0
    The minimum opacity for the heatmap.
max_opacity: default 0.6
    The maximum opacity for the heatmap.
scale_radius: default False
    Scale the radius of the points based on the zoom level.
gradient: dict, default None
    Match point density values to colors. Color can be a name ('red'),
    RGB values ('rgb(255,0,0)') or a hex number ('#FF0000').
use_local_extrema: default False
    Defines whether the heatmap uses a global extrema set found from the input data
    OR a local extrema (the maximum and minimum of the currently displayed view).
auto_play: default False
    Automatically play the animation across time.
display_index: default True
    Display the index (usually time) in the time control.
index_steps: default 1
    Steps to take in the index dimension between animation steps.
min_speed: default 0.1
    Minimum fps speed for animation.
max_speed: default 10
    Maximum fps speed for animation.
speed_step: default 0.1
    Step between different fps speeds on the speed slider.
position: default 'bottomleft'
    Position string for the time slider. Format: 'bottom/top'+'left/right'.
overlay : bool, default True
    Adds the layer as an optional overlay (True) or the base layer (False).
control : bool, default True
    Whether the Layer will be included in LayerControls.
show: bool, default True
    Whether the layer will be shown on opening (only for overlays).
File:           c:\users\miguel angel\appdata\local\programs\python\python37\lib\site-packages\folium\plugins\heat_map_withtime.py
Type:           type
Subclasses:

In [39]:
# len(heatmap_time_data)

In [40]:
# heatmap_time_dates

In [51]:
# heat map over time

# data
# take note of data format needed for heat map with time (using plugins.HeatMapWithTime?)
heatmap_time_data = (np.random.random((100,20,2)) + np.array([[39, -98]])).tolist()

# dates
heatmap_time_dates = [d.strftime('%Y-%m-%d') for d in pd.date_range('20160101', periods=len(heatmap_time_data))]

# map
map_heatmap_time = folium.Map([39, -98], tiles='CartoDB Dark_Matter', zoom_start=6)

# heatmap plugin
heatmap_time_plugin = plugins.HeatMapWithTime(heatmap_time_data, index=heatmap_time_dates)

# add heatmap plugin to map
heatmap_time_plugin.add_to(map_heatmap_time)

# display map
map_heatmap_time

# Latitude and Longitude Tool

In [42]:
# map
map_lat_long = folium.Map(location=[38, -98], zoom_start=4)

# add latitude and longitude tool to map
map_lat_long.add_child(folium.LatLngPopup())

# display map
map_lat_long

# Measure Control

In [53]:
# map
map_measure = folium.Map([40, -100], zoom_start=4)

# measure control
measure_control = plugins.MeasureControl(position='topleft', 
                                         active_color='red', 
                                         completed_color='red', 
                                         primary_length_unit='meters')

# add measure control to map
map_measure.add_child(measure_control)

# display map
map_measure

In [ ]:
plugins.MeasureControl?

# Dual Map

In [54]:
# dual map
map_dual = plugins.DualMap(location=[40, -98], tiles=None, zoom_start=4)

# map tiles
folium.TileLayer('Stamen Terrain').add_to(map_dual)
folium.TileLayer('CartoDB Positron').add_to(map_dual)

# add layer control to maps
folium.LayerControl().add_to(map_dual)

# display map(s)
map_dual

# Draw

In [55]:
# map
map_draw = folium.Map(location=[40, -99], zoom_start=4)

# draw tools
# export=True exports the drawn shapes as a geojson file
draw = plugins.Draw(export=True)

# add draw tools to map
draw.add_to(map_draw)

# display map
map_draw

In [ ]:
plugins.Draw?

# Overlay Image

In [62]:
# map
# map of Africa flags from Wikipedia
map_img_overlay = folium.Map([2,22], zoom_start=3, tiles='CartoDB Positron')

# image to overlay on map
img_overlay = folium.raster_layers.ImageOverlay(name='flags of Africa', 
                                                image='flags_of_africa.png',
                                                # bounds - [[lat_min, lon_min], [lat_max, lon_max]]
                                                bounds=[[-38, -28], [40, 60]],
                                                opacity=0.5)
# add image to map
img_overlay.add_to(map_img_overlay)

# layer control to click layer on or off
folium.LayerControl().add_to(map_img_overlay)

# display map
map_img_overlay

# Maps with Interactive Widgets

In [60]:
import geocoder
import ipywidgets

# text widget
address_text_box = ipywidgets.Text(value='', placeholder='type here', description='address:')

# widget function
def plot_locations(address):
    # location address
    location = geocoder.osm(address)
    
    # latitude and longitude of location
    latlng = [location.lat, location.lng]
    
    # create map
    plot_locations_map = folium.Map(location=[40, -100], zoom_start=4)
    
    # marker
    folium.Marker(latlng, popup=str(address), tooltip='click').add_to(plot_locations_map)
    
    # display map
    display(plot_locations_map)
    
# interaction between widget and function    
ipywidgets.interact_manual(plot_locations, address=address_text_box)

'''
test addresses
4790 W 16th St, Indianapolis, IN 46222 (Indy 500 Track)
2920 Zoo Dr, San Diego, CA 92101 (San Diego Zoo)
1 Infinite Loop, Cupertino, CA 95014 (Apple)
'''

interactive(children=(Text(value='', description='address:', placeholder='type here'), Button(description='Run…

'\ntest addresses\n4790 W 16th St, Indianapolis, IN 46222 (Indy 500 Track)\n2920 Zoo Dr, San Diego, CA 92101 (San Diego Zoo)\n1 Infinite Loop, Cupertino, CA 95014 (Apple)\n'

In [54]:
import geopy.distance

# text widgets
route_start_widget = ipywidgets.Text(value='', placeholder='address', description='start:')
route_stop_widget = ipywidgets.Text(value='', placeholder='address', description='stop:')

# widget function
def get_distance(start_address, stop_address):
    
    # string addresses to location information
    start_location = geocoder.osm(start_address)
    stop_location = geocoder.osm(stop_address)
    
    # pull out latitude and longitude from location information
    start_latlng = [start_location.lat, start_location.lng]
    stop_latlng = [stop_location.lat, stop_location.lng]
    
    # calculate distance from start point to stop point using latitudes and longitudes
    distance = geopy.distance.distance(start_latlng, stop_latlng).miles
    print(f'distance: {distance:.2f} miles')
    
    # map
    distance_path = [(start_latlng), (stop_latlng)]
    map_distance = folium.Map(location=[38, -98], zoom_start=4)
    plugins.AntPath(distance_path).add_to(map_distance)
    display(map_distance)
    
# interaction between widgets and function    
ipywidgets.interact_manual(get_distance, start_address=route_start_widget, stop_address=route_stop_widget)

# notice animation moves in the direction from start to stop and distance prints above map

interactive(children=(Text(value='', description='start:', placeholder='address'), Text(value='', description=…

# Spain Choropleth

In [55]:
# MAPA DE TOTAL DE DECESOS 
import pandas as pd
data_total_mean = pd.read_csv('decesos_espania.csv', sep=';')
 
# Initialize the map:
m = folium.Map(location=[42.1257, -8], zoom_start = 5)

# add tile layers to the map
# con esto posibilito que luego en el mapa pueda elegir el 'tipo de vista'
tiles = ['stamenwatercolor','cartodbpositron','openstreetmap','stamenterrain']
for tile in tiles:
    folium.TileLayer(tile).add_to(m)
    
 
# Add the color for the chloropleth:
m.choropleth(
 geo_data='provincias-espanolas 2.0.geojson',
 name='choropleth',
 data=data_total_mean,
 columns=['Comunidad Autónoma', 'Todas las causas'],
 key_on='feature.properties.ccaa',   # dentro del 'geojson', viendo su estructura de datos
 fill_color='BuPu',
 fill_opacity=0.7,
 line_opacity=0.2,
 legend_name='Decesos por comunidad autonoma'
)
folium.LayerControl().add_to(m)

m

C:\Users\Miguel Angel\AppData\Local\Programs\Python\Python37\lib\site-packages\folium\folium.py:413: FutureWarning: The choropleth  method has been deprecated. Instead use the new Choropleth class, which has the same arguments. See the example notebook 'GeoJSON_and_choropleth' for how to do this.
  FutureWarning