In [3]:
!pip install pandas==1.3.6

Note: you may need to restart the kernel to use updated packages.

ERROR: Could not find a version that satisfies the requirement sqlite3 (from versions: none)
ERROR: No matching distribution found for sqlite3
WARNING: You are using pip version 22.0.4; however, version 24.0 is available.
You should consider upgrading via the 'c:\Users\david\AppData\Local\Programs\Python\Python37\python.exe -m pip install --upgrade pip' command.

In [6]:
pip freeze

absl-py==1.0.0
adal==1.2.7
aiodns==3.0.0
aiohttp==3.8.1
aiohttp-socks==0.7.1
aiosignal==1.2.0
alembic==1.7.7
altair==4.2.0
applicationinsights==0.11.10
argcomplete==2.0.0
argon2-cffi==21.3.0
argon2-cffi-bindings==21.2.0
astor==0.8.1
astunparse==1.6.3
async-timeout==4.0.2
asynctest==0.13.0
atomicwrites==1.4.0
attrs==21.4.0
autopage==0.5.0
azure-common==1.1.28
azure-core==1.22.1
azure-graphrbac==0.61.1
azure-mgmt-authorization==2.0.0
azure-mgmt-containerregistry==9.1.0
azure-mgmt-core==1.3.0
azure-mgmt-keyvault==9.3.0
azure-mgmt-resource==21.0.0
azure-mgmt-storage==20.0.0
azureml-core==1.42.0.post1
azureml-dataprep-native==38.0.0
azureml-dataprep-rslex==2.6.3
backcall==0.2.0
backports.tempfile==1.0
backports.weakref==1.0.post1
backports.zoneinfo==0.2.1
base58==2.1.1
bcrypt==3.2.2
beautifulsoup4==4.10.0
bleach==4.1.0
blinker==1.4
blis==0.7.7
branca==0.4.2
Brownie==0.5.1
bs4==0.0.1
cached-property==1.5.2
cachetools==5.0.0
catalogue==2.0.7
catboost==1.0.5
category-encoders==2.4.0
cchardet==2.1.7
certifi==2021.10.8
cffi==1.15.0
charset-normalizer==2.0.12
chart-studio==1.1.0
click==8.0.4
cliff==3.10.1
cloudpickle==2.0.0
cmaes==0.8.2
cmd2==2.4.1
cmdstanpy==0.9.5
colorama==0.4.4
colorlog==6.6.0
colour==0.1.5
contextlib2==21.6.0Note: you may need to restart the kernel to use updated packages.
convertdate==2.4.0
cryptography==36.0.2
cycler==0.11.0
cymem==2.0.6
Cython==0.29.28
dash==2.8.1
dash-core-components==2.0.0
dash-html-components==2.0.0
dash-table==5.0.0
dateparser==1.1.1
debugpy==1.5.1
decorator==5.1.1
DeFiLlama==1.1.0
defusedxml==0.7.1
docker==5.0.3
dtreeviz==1.3.5
elastic-transport==8.1.2
elasticsearch==8.2.0
eli5==0.11.0
en-core-web-lg @ https://github.com/explosion/spacy-models/releases/download/en_core_web_lg-3.2.0/en_core_web_lg-3.2.0-py3-none-any.whl
entrypoints==0.3
ephem==4.1.3
es-core-news-lg @ https://github.com/explosion/spacy-models/releases/download/es_core_news_lg-3.2.0/es_core_news_lg-3.2.0-py3-none-any.whl
et-xmlfile==1.1.0
fake-useragent==0.1.11
Faker==13.12.0
findspark==2.0.1
Flask==2.1.2
flatbuffers==2.0
folium==0.12.1.post1
fonttools==4.29.1
frozenlist==1.3.0
fusepy==3.0.1
future==0.18.2
gast==0.5.3
geocoder==1.38.1
geographiclib==1.52
geopy==2.2.0
gitdb==4.0.9
GitPython==3.1.27
google-auth==2.6.2
google-auth-oauthlib==0.4.6
google-pasta==0.2.0
googletransx==2.4.2
graphviz==0.20
greenlet==1.1.2
grpcio==1.45.0
gym==0.23.1
gym-notices==0.0.6
h5py==3.6.0
hijri-converter==2.2.3
holidays==0.13
htmlmin==0.1.12
humanfriendly==10.0
idna==3.3
ImageHash==4.2.1
imageio==2.16.0
importlib-metadata==4.11.2
importlib-resources==5.4.0
inflection==0.5.1
iniconfig==1.1.1
investpy==1.0.8
ipykernel==6.7.0
ipython==7.31.1
ipython-genutils==0.2.0
ipywidgets==7.6.5
isodate==0.6.1
itsdangerous==2.1.2
jedi==0.18.1
jeepney==0.8.0
Jinja2==3.0.3
jmespath==1.0.0
joblib==1.0.1
jsonpickle==2.2.0
jsonschema==4.4.0
jupyter-client==7.1.2
jupyter-core==4.9.1
jupyterlab-pygments==0.1.2
jupyterlab-widgets==1.0.2
keras==2.8.0
Keras-Preprocessing==1.1.2
kiwisolver==1.3.2

knack==0.9.0
korean-lunar-calendar==0.2.1
langcodes==3.3.0
libclang==13.0.0
lightgbm==3.3.2
llvmlite==0.38.0
LunarCalendar==0.0.9
lxml==4.8.0
Mako==1.2.0
Markdown==3.3.6
MarkupSafe==2.0.1
matplotlib==3.5.1
matplotlib-inline==0.1.3
missingno==0.5.1
mistune==0.8.4
mljar-supervised==0.11.2
more-itertools==8.12.0
msal==1.18.0
msal-extensions==1.0.0
msrest==0.6.21
msrestazure==0.6.4
multidict==6.0.2
multimethod==1.8
multitasking==0.0.10
murmurhash==1.0.7
mysql-connector-python==8.0.27
nbclient==0.5.12
nbconvert==6.4.2
nbformat==5.1.3
ndg-httpsclient==0.5.1
nest-asyncio==1.5.4
networkx==2.6.3
nltk==3.7
notebook==6.4.8
numba==0.55.1
numpy==1.21.5
oauthlib==3.2.0
opencv-python==4.5.5.64
openpyxl==3.0.9
opt-einsum==3.3.0
optuna==2.10.0
packaging==21.3
pandas==1.3.5
pandas-datareader==0.10.0
pandas-profiling==3.1.0
pandocfilters==1.5.0
paramiko==2.11.0
parso==0.8.3
pathspec==0.9.0
pathy==0.6.1
patsy==0.5.2
pbr==5.8.1
phik==0.12.2
pickleshare==0.7.5
Pillow==9.0.1
pkginfo==1.8.3
plotly==5.6.0
pluggy==1.0.0
pmdarima==1.8.5
portalocker==2.4.0
preshed==3.0.6
prettytable==3.2.0
prometheus-client==0.13.1
prompt-toolkit==3.0.26
protobuf==3.19.4
py==1.11.0
py4j==0.10.9.3
pyarrow==3.0.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycares==4.1.2
pycoingecko==2.2.0
pycparser==2.21
pydantic==1.8.2
pydeck==0.7.1
Pygments==2.11.2
PyJWT==2.4.0
PyMeeus==0.5.11
pymongo==4.1.1
Pympler==1.0.1
PyMySQL==1.0.2
PyNaCl==1.5.0
pyOpenSSL==22.0.0
pyparsing==3.0.7
pyperclip==1.8.2
pyreadline==2.1
pyreadline3==3.4.1
pyrsistent==0.18.1
PySocks==1.7.1
pyspark==3.2.1
pystan==2.19.1.1
pytest==7.1.1
python-binance==1.0.15
python-dateutil==2.8.2
python-socks==2.0.3
pytz==2021.3
pytz-deprecation-shim==0.1.0.post0
PyWavelets==1.2.0
pywin32==227
pywinpty==2.0.5
PyYAML==6.0
pyzmq==22.3.0
Quandl==3.7.0
ratelim==0.1.6
regex==2022.3.2
requests==2.27.1
requests-oauthlib==1.3.1
retrying==1.3.3
rsa==4.8
schedule==1.1.0
scikit-image==0.19.1
scikit-learn==1.0.2
scikit-plot==0.3.7
scipy==1.7.3
seaborn==0.11.2
SecretStorage==3.3.2
semver==2.13.0
Send2Trash==1.8.0
setuptools-git==1.2
shap==0.36.0
six==1.16.0
sklearn==0.0
slicer==0.0.7
smart-open==5.2.1
smmap==5.0.0
soupsieve==2.3.1
spacy==3.2.4
spacy-legacy==3.0.9
spacy-loggers==1.0.2
SQLAlchemy==1.4.35
squarify==0.4.3
srsly==2.4.3
statsmodels==0.13.2
stevedore==3.5.0
streamlit==1.7.0
tabulate==0.8.9
tangled-up-in-unicode==0.1.0
tenacity==8.0.1
tensorboard==2.8.0
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.8.1
tensorflow==2.8.0
tensorflow-io-gcs-filesystem==0.24.0
termcolor==1.1.0
terminado==0.13.2
testpath==0.6.0
tf-estimator-nightly==2.8.0.dev2021122109
thinc==8.0.15
threadpoolctl==3.1.0
tifffile==2021.11.2
toml==0.10.2
tomli==2.0.1
toolz==0.11.2
tornado==6.1
tqdm==4.64.0
traitlets==5.1.1
tweepy==4.10.0
twint==2.1.20
typer==0.4.1
typing-extensions==3.10.0.2
tzdata==2021.5
tzlocal==4.1
ujson==5.1.0
Unidecode==1.3.3
urllib3==1.26.8
validators==0.18.2
vega-datasets==0.9.0
visions==0.7.4
wasabi==0.9.1
watchdog==2.1.6
wcwidth==0.2.5
webencodings==0.5.1
websocket-client==1.3.2
websockets==9.1
Werkzeug==2.1.1
widgetsnbextension==3.5.2
wordcloud==1.8.1
wrapt==1.14.0
xgboost==1.5.2
yarl==1.7.2
yfinance==0.1.70
zipp==3.7.0

In [7]:
import pandas as pd
import sqlite3

In [8]:
# Conectamos con la base de datos chinook.db
connection = sqlite3.connect("data/my_database.db")

# Obtenemos un cursor que utilizaremos para hacer las queries
crsr = connection.cursor()

In [9]:
res = crsr.execute("SELECT name FROM sqlite_master WHERE type='table'")
for name in res:
    print(name[0])

cervezas

In [10]:
# Con esta función leemos los datos y lo pasamos a un DataFrame de Pandas
def sql_query(query):

    # Ejecuta la query
    crsr.execute(query)

    # Almacena los datos de la query
    ans = crsr.fetchall()

    # Obtenemos los nombres de las columnas de la tabla
    names = [description[0] for description in crsr.description]

    return pd.DataFrame(ans,columns=names)

In [23]:
query = '''
DROP TABLE cerveza (
    CodC VARCHAR(2) NOT NULL PRIMARY KEY,
    Envase VARCHAR(32) NULL,
    Capacidad FLOAT(2) NULL,
    Stock INT(5) NULL,
)
'''

crsr.execute(query)

OperationalError: near ")": syntax error

In [16]:
res = crsr.execute("SELECT name FROM sqlite_master WHERE type='table'")
for name in res:
    print(name[0])

cervezas
cerveza

In [17]:
query = '''
SELECT * FROM cerveza
'''
sql_query(query)

Empty DataFrame
Columns: [CodC, Envase, Capacidad, Stock]
Index: []

In [10]:
# query = '''
# DROP TABLE cervezas 
# '''
# crsr.execute(query)

In [18]:
query = '''
INSERT INTO cerveza (CodC, Envase, Capacidad, Stock)
VALUES ('01','Botella',0.2,3600)
'''
crsr.execute(query)

In [20]:
query = '''
SELECT * FROM cerveza
'''
sql_query(query)

  CodC   Envase  Capacidad  Stock
0   01  Botella        0.2   3600

In [24]:
query = '''
INSERT INTO cerveza VALUES ('02','Botella',0.33,1200)
'''
crsr.execute(query)

In [39]:
query = '''
INSERT INTO cerveza VALUES
('05','Barril',60,30)
'''
crsr.execute(query)

In [27]:
query = '''
SELECT * FROM cerveza
'''
sql_query(query)

  CodC   Envase  Capacidad  Stock
0   01  Botella       0.20   3600
1   02  Botella       0.33   1200
2   03     Lata       0.33   2400
3   04  Botella       1.00    288
4   05   Barril      60.00     30

## DataFame a BD sql

[pandas.DataFrame.to_sql](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_sql.html)

In [20]:
query = '''
SELECT * FROM cervezas 
'''
sql_query(query)

  CodC   Envase  Capacidad  Stock
0   01  Botella       0.20   3600
1   02  Botella       0.33   1200
2   03     Lata       0.33   2400
3   04  Botella       1.00    288
4   05   Barril      60.00     30

In [33]:
query = '''
UPDATE cerveza
SET Stock = 5000,  Envase = 'Lata', Capacidad = 0.25
WHERE CodC='02';
'''
crsr.execute(query)

In [35]:
query = '''
SELECT * FROM cerveza
'''
sql_query(query)

  CodC   Envase  Capacidad  Stock
0   01  Botella       0.20   3600
1   02     Lata       0.25   5000
2   03     Lata       0.33   2400
3   04  Botella       1.00    288
4   05   Barril      60.00     30

In [36]:
query = '''
DELETE FROM cerveza WHERE CodC='05';
'''
crsr.execute(query)

In [40]:
query = '''
SELECT * FROM cerveza
'''
sql_query(query)

  CodC   Envase  Capacidad  Stock
0   01  Botella       0.20   3600
1   02     Lata       0.25   5000
2   03     Lata       0.33   2400
3   04  Botella       1.00    288
4   05   Barril      60.00     30

## SUBQUERIES

In [42]:
query = '''
SELECT * FROM (SELECT * FROM cerveza WHERE Envase="Lata")
'''
sql_query(query)

  CodC Envase  Capacidad  Stock
0   02   Lata       0.25   5000
1   03   Lata       0.33   2400

In [28]:
# ATENCIÓN! Al terminar hay que cerrar la conexión a la DB para que se guarden los cambios!!!!!!
connection.commit()
connection.close()